# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pedro Henrique de Oliveira Silva (Pedro Hos)
title: Senior Software Maintenance Engineer @ Red Hat
email: pedro-hos@outlook.com
website: www.github.com/pedro-hos

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  pedro-hos
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: pedrohosilva
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: @jugvale3355
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: blog
  icon: fas fa-globe
  url: https://pedrohosilva.wordpress.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pedro Hos and I'm a Senior Software Maintenance Engineer @ Red Hat with +10 years of IT experience. I am JUG Vale co-leader, Open Source, and Open Data enthusiast. As well as developer systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills. I am currently studying Data Science, Machine Learning and IA stuff.

  I am most skilled in: <mark>Java</mark>, <mark>Wildfly</mark>, <mark>Keycloak</mark>, <mark>Spring-boot</mark>, <mark>Quakus</mark>, <mark>JS</mark> and begginer in another languages like: <mark>R</mark>, <mark>Python</mark> and <mark>Go</mark>. Finnaly I have worked also with <mark>Docker</mark> and <mark>Podman</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Temis API
        link: https://github.com/sjcdigital/temis-api
        # link_text: Project Website
        additional_links:
          - title:  sjcdigital/temis-api
            icon: fab fa-github
            url: github.com/sjcdigital/temis-api
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is a web scraping project that I created to "get" law project from my city São José dos Campos and other politician information and deliver it on a REST API. Was build using <mark>Java</mark>, <mark>JSoup</mark>, <mark>JMS</mark>, <mark>MySQL</mark>
      - layout: top-middle
        title: Orçamento Secreto
        link: https://github.com/sjcdigital/data-analizes/tree/main/orcamento-secreto
        # link_text: Project Website
        additional_links:
          - title:  sjcdigital/data-analizes
            icon: fab fa-github
            url: github.com/sjcdigital/data-analizes/tree/main/orcamento-secreto
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is a web scraping project that I created to "get" secret budgets from Brazil that was not easily visible. So I got this information from the transparency portal and also collected the receiver's budget information through their documents. All information is avaible on a Postgres database dump. 
          
          Technologies used: <mark>Java</mark>, <mark>Quarkus</mark>, <mark>Apache Camel</mark>, <mark>JSoup</mark> and <mark>Postgres</mark>.
      - layout: top-middle
        title: Urbam Deaths
        link: https://github.com/sjcdigital/urbam-deaths
        # link_text: Project Website
        additional_links:
          - title:  sjcdigital/urbam-deaths
            icon: fab fa-github
            url: https://github.com/sjcdigital/urbam-deaths
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is a web scraping project that I created to collect possible "Covid 19" deaths from my city São José dos Campos from the funeral service and generate a CSV and JSON files.
          
          Technologies used: <mark>Java</mark>, <mark>Quarkus</mark> and <mark>JSoup</mark>.
      - layout: top-middle
        title: Leo Crawler
        link: https://github.com/sjcdigital/queimadas-data/tree/master/leo-crawler
        # link_text: Project Website
        additional_links:
          - title:  sjcdigital/queimadas-data
            icon: fab fa-github
            url: https://github.com/sjcdigital/queimadas-data/tree/master/leo-crawler
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is a web scraping project that I created to collect possible burning forests happening in Brazil from the INPE site. 
          Technologies used: <mark>Java</mark>, <mark>Quarkus</mark>.
      - layout: top-middle
        title: Como Anda a Ciclovia?
        link: https://github.com/sjcdigital/como-anda-a-ciclovia
        # link_text: Project Website
        additional_links:
          - title:  sjcdigital/como-anda-a-ciclovia
            icon: fab fa-github
            url: https://github.com/sjcdigital/como-anda-a-ciclovia
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is a web site create to monitor and detect cliclopaths conditions. 
          Technologies used: <mark>Java</mark>, <mark>Quarkus</mark>, <mark>MySQL</mark>
      - layout: top-middle
        title: quarkus-file-vault
        link: https://github.com/quarkiverse/quarkus-file-vault
        # link_text: Project Website
        additional_links:
          - title:  quarkiverse/quarkus-file-vault
            icon: fab fa-github
            url: https://github.com/quarkiverse/quarkus-file-vault
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          I've helped to implement a new feature on Quarkus File Vault that can be used to encrypt a keystore password in order to mask it.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Red Hat
        link: redhat.com
        # link_text: boringcompany.com
        sub_title: Senior Software Maintenance Engineer
        caption: September 2021 - Present
        description: | # this will include new lines to allow paragraphs
            Java Products Maintenance by creating patches, sample applications, and writing articles to guide customers to use product features and documentation. I am the current JBoss Security Lead (SBR Coach) working with RH-SSO (Keycloak) and JBoss EAP Elytron (Wildfly Elytron).
      - layout: left
        title: Red Hat
        link: redhat.com
        # link_text: boringcompany.com
        sub_title: Software Maintenance Engineer
        caption: March 2017 - September 2021
        description: | # this will include new lines to allow paragraphs
            Java Products Maintenance by creating patches, sample application and writing articles to guide customers to use product features and documentation.
      - layout: left
        title: GSW Soluções Integradas
        link: www.gsw.com.br
        # link_text: boringcompany.com
        sub_title: Senior Full Stack Developer
        caption: March 2016 - March 2017
        description: | # this will include new lines to allow paragraphs
            Developing applications with <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>Rabbit MQ</mark>, <mark>Angular JS</mark> etc.
      - layout: left
        title: Gauge
        link: gauge.digital
        # link_text: boringcompany.com
        sub_title: Java Developer
        caption: March 2015 - March 2016
        description: | # this will include new lines to allow paragraphs
            Developing web applications with <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>Redis</mark>, <mark>Oracle</mark>, <mark>MongoDB</mark> etc.
      - layout: left
        title: GSW Soluções Integradas
        link: www.gsw.com.br
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: March 2014 - March 2015
        description: | # this will include new lines to allow paragraphs
            Developing applications with <mark>Java</mark>, <mark>Spring Boot</mark>, <mark>Rabbit MQ</mark>, <mark>Angular JS</mark> etc.
      - layout: left
        title: Superpay Gateway de Pagamentos
        #link: www.gsw.com.br
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: March 2013 - March 2014
        description: | # this will include new lines to allow paragraphs
            Developing applications with <mark>Java</mark>, <mark>Spring</mark>, <mark>SOAP</mark>, <mark>REST</mark>, <mark>MySQL</mark> etc.
      - layout: left
        title: Focusnetworks Tecnologia
        link: www.focusnetworks.com.br/
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: March 2013 - May 2013
        description: | # this will include new lines to allow paragraphs
            Developing applications with <mark>Java</mark>, <mark>Spring</mark>, <mark>SOAP</mark>, <mark>REST</mark>, <mark>MySQL</mark> etc.
      - layout: left
        title: SSLTi Tecnlogia
        #link: www.focusnetworks.com.br/
        # link_text: boringcompany.com
        sub_title: Intern Software Developer
        caption: January 2012 - March 2013
        description: | # this will include new lines to allow paragraphs
            Java desktop developer with <mark>JavaFx</mark> and <mark>Oracle</mark> to read tags RFID
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FATEC Prof. Jessen Vidal
        caption: 2008 - 2012
        sub_title: Bachelor of Science in Information Technology, Databases Emphasis
        description: | # this will include new lines to allow paragraphs
          During my time at Fatec I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines.

          I spent a lot of my free time as a committee member of the *VESTEC Course* taking on roles *Vice-President* and *Math Teacher*.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: USP/ESALQ
        caption: 2021 - 2022
        sub_title: Post-Graduation in Data Science, Machine Learning, and Analytics
        description: | # this will include new lines to allow paragraphs
          I am finishing my Post-Graduation in Data Science at USP, and the time spent studying there was good to understand better some IA and Data Science concepts.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - I make some "cachaça"
      - Moutain biker
      - Writter, with 2 books published: ["Kim, O corpo seco"](https://kotter.com.br/loja/kim-o-corpo-seco-pedro-hos/) my first novel and "[Pés no chão"](https://www.amazon.com.br/P%C3%A9s-no-ch%C3%A3o-Pedro-Hos-ebook/dp/B089M8PZB7)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
